/**
 * Things Keeper
 * Will save your notes.
 *
 * OpenAPI spec version: 0.2.0
 * Contact: vrahlinskiy@cinimex.ru
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { URI } from './uRI';
import { URL } from './uRL';


export interface Resource { 
    description?: string;
    file?: any;
    filename?: string;
    inputStream?: any;
    open?: boolean;
    readable?: boolean;
    uri?: URI;
    url?: URL;
}

