/**
 * Things Keeper
 * Will save your notes.
 *
 * OpenAPI spec version: 0.2.0
 * Contact: vrahlinskiy@cinimex.ru
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ImageDto } from './imageDto';


export interface StepDto { 
    description?: string;
    id?: string;
    image?: ImageDto;
    stepNumber?: number;
    title?: string;
}

