/**
 * Things Keeper
 * Will save your notes.
 *
 * OpenAPI spec version: 0.2.0
 * Contact: vrahlinskiy@cinimex.ru
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { AuthRequest } from '../model/authRequest';
import { AuthResponse } from '../model/authResponse';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable({
  providedIn: 'root'
})
export class AuthControllerService {

    protected basePath = 'http://localhost:8080/api/meta';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {

        if (configuration) {
            this.configuration = configuration;
            this.configuration.basePath = configuration.basePath || basePath || this.basePath;

        } else {
            this.configuration.basePath = basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * login
     * 
     * @param auth auth
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public loginUsingPOST(auth: AuthRequest, observe?: 'body', reportProgress?: boolean): Observable<AuthResponse>;
    public loginUsingPOST(auth: AuthRequest, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<AuthResponse>>;
    public loginUsingPOST(auth: AuthRequest, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<AuthResponse>>;
    public loginUsingPOST(auth: AuthRequest, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (auth === null || auth === undefined) {
            throw new Error('Required parameter auth was null or undefined when calling loginUsingPOST.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        const httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<AuthResponse>(`${this.configuration.basePath}/auth/login`,
            auth,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * register
     * 
     * @param auth auth
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public registerUsingPOST(auth: AuthRequest, observe?: 'body', reportProgress?: boolean): Observable<AuthResponse>;
    public registerUsingPOST(auth: AuthRequest, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<AuthResponse>>;
    public registerUsingPOST(auth: AuthRequest, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<AuthResponse>>;
    public registerUsingPOST(auth: AuthRequest, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (auth === null || auth === undefined) {
            throw new Error('Required parameter auth was null or undefined when calling registerUsingPOST.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        const httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<AuthResponse>(`${this.configuration.basePath}/auth/register`,
            auth,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
